//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS2.SCache.WCFService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFService.IWebServer")]
    public interface IWebServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServer/SetString", ReplyAction="http://tempuri.org/IWebServer/SetStringResponse")]
        void SetString(string key, string value, System.DateTime ExpirationTime, string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServer/SetString", ReplyAction="http://tempuri.org/IWebServer/SetStringResponse")]
        System.Threading.Tasks.Task SetStringAsync(string key, string value, System.DateTime ExpirationTime, string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServer/GetString", ReplyAction="http://tempuri.org/IWebServer/GetStringResponse")]
        string GetString(string key, string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServer/GetString", ReplyAction="http://tempuri.org/IWebServer/GetStringResponse")]
        System.Threading.Tasks.Task<string> GetStringAsync(string key, string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServer/SetDataTable", ReplyAction="http://tempuri.org/IWebServer/SetDataTableResponse")]
        void SetDataTable(string key, System.Data.DataTable value, System.DateTime ExpirationTime, string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServer/SetDataTable", ReplyAction="http://tempuri.org/IWebServer/SetDataTableResponse")]
        System.Threading.Tasks.Task SetDataTableAsync(string key, System.Data.DataTable value, System.DateTime ExpirationTime, string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServer/GetDataTable", ReplyAction="http://tempuri.org/IWebServer/GetDataTableResponse")]
        System.Data.DataTable GetDataTable(string key, string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServer/GetDataTable", ReplyAction="http://tempuri.org/IWebServer/GetDataTableResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetDataTableAsync(string key, string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServer/SetIncrement", ReplyAction="http://tempuri.org/IWebServer/SetIncrementResponse")]
        void SetIncrement(string key, System.DateTime ExpirationTime, string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServer/SetIncrement", ReplyAction="http://tempuri.org/IWebServer/SetIncrementResponse")]
        System.Threading.Tasks.Task SetIncrementAsync(string key, System.DateTime ExpirationTime, string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServer/GetIncrement", ReplyAction="http://tempuri.org/IWebServer/GetIncrementResponse")]
        int GetIncrement(string key, string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServer/GetIncrement", ReplyAction="http://tempuri.org/IWebServer/GetIncrementResponse")]
        System.Threading.Tasks.Task<int> GetIncrementAsync(string key, string hash);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebServerChannel : SS2.SCache.WCFService.IWebServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServerClient : System.ServiceModel.ClientBase<SS2.SCache.WCFService.IWebServer>, SS2.SCache.WCFService.IWebServer {
        
        public WebServerClient() {
        }
        
        public WebServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SetString(string key, string value, System.DateTime ExpirationTime, string hash) {
            base.Channel.SetString(key, value, ExpirationTime, hash);
        }
        
        public System.Threading.Tasks.Task SetStringAsync(string key, string value, System.DateTime ExpirationTime, string hash) {
            return base.Channel.SetStringAsync(key, value, ExpirationTime, hash);
        }
        
        public string GetString(string key, string hash) {
            return base.Channel.GetString(key, hash);
        }
        
        public System.Threading.Tasks.Task<string> GetStringAsync(string key, string hash) {
            return base.Channel.GetStringAsync(key, hash);
        }
        
        public void SetDataTable(string key, System.Data.DataTable value, System.DateTime ExpirationTime, string hash) {
            base.Channel.SetDataTable(key, value, ExpirationTime, hash);
        }
        
        public System.Threading.Tasks.Task SetDataTableAsync(string key, System.Data.DataTable value, System.DateTime ExpirationTime, string hash) {
            return base.Channel.SetDataTableAsync(key, value, ExpirationTime, hash);
        }
        
        public System.Data.DataTable GetDataTable(string key, string hash) {
            return base.Channel.GetDataTable(key, hash);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetDataTableAsync(string key, string hash) {
            return base.Channel.GetDataTableAsync(key, hash);
        }
        
        public void SetIncrement(string key, System.DateTime ExpirationTime, string hash) {
            base.Channel.SetIncrement(key, ExpirationTime, hash);
        }
        
        public System.Threading.Tasks.Task SetIncrementAsync(string key, System.DateTime ExpirationTime, string hash) {
            return base.Channel.SetIncrementAsync(key, ExpirationTime, hash);
        }
        
        public int GetIncrement(string key, string hash) {
            return base.Channel.GetIncrement(key, hash);
        }
        
        public System.Threading.Tasks.Task<int> GetIncrementAsync(string key, string hash) {
            return base.Channel.GetIncrementAsync(key, hash);
        }
    }
}
