#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS2.SFile.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LygcjDB")]
	public partial class FSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertFS_DIR(FS_DIR instance);
    partial void UpdateFS_DIR(FS_DIR instance);
    partial void DeleteFS_DIR(FS_DIR instance);
    partial void InsertFS_FILE(FS_FILE instance);
    partial void UpdateFS_FILE(FS_FILE instance);
    partial void DeleteFS_FILE(FS_FILE instance);
    #endregion
		
		public FSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<FS_DIR> FS_DIR
		{
			get
			{
				return this.GetTable<FS_DIR>();
			}
		}
		
		public System.Data.Linq.Table<FS_FILE> FS_FILE
		{
			get
			{
				return this.GetTable<FS_FILE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FS_DIR")]
	public partial class FS_DIR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _ParentID;
		
		private string _Name;
		
		private string _IDPath;
		
		private string _NamePath;
		
		private string _Icon;
		
		private int _DirType;
		
		private int _TotalFileCount;
		
		private long _TotalFileSize;
		
		private string _TotalFileSizeText;
		
		private string _CreateUserID;
		
		private string _CreateUserName;
		
		private System.DateTime _CreateTime;
		
		private bool _IsHide;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnParentIDChanging(string value);
    partial void OnParentIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnIDPathChanging(string value);
    partial void OnIDPathChanged();
    partial void OnNamePathChanging(string value);
    partial void OnNamePathChanged();
    partial void OnIconChanging(string value);
    partial void OnIconChanged();
    partial void OnDirTypeChanging(int value);
    partial void OnDirTypeChanged();
    partial void OnTotalFileCountChanging(int value);
    partial void OnTotalFileCountChanged();
    partial void OnTotalFileSizeChanging(long value);
    partial void OnTotalFileSizeChanged();
    partial void OnTotalFileSizeTextChanging(string value);
    partial void OnTotalFileSizeTextChanged();
    partial void OnCreateUserIDChanging(string value);
    partial void OnCreateUserIDChanged();
    partial void OnCreateUserNameChanging(string value);
    partial void OnCreateUserNameChanged();
    partial void OnCreateTimeChanging(System.DateTime value);
    partial void OnCreateTimeChanged();
    partial void OnIsHideChanging(bool value);
    partial void OnIsHideChanged();
    #endregion
		
		public FS_DIR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="NVarChar(200)")]
		public string ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this.OnParentIDChanging(value);
					this.SendPropertyChanging();
					this._ParentID = value;
					this.SendPropertyChanged("ParentID");
					this.OnParentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(200)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPath", DbType="NVarChar(200)")]
		public string IDPath
		{
			get
			{
				return this._IDPath;
			}
			set
			{
				if ((this._IDPath != value))
				{
					this.OnIDPathChanging(value);
					this.SendPropertyChanging();
					this._IDPath = value;
					this.SendPropertyChanged("IDPath");
					this.OnIDPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamePath", DbType="NVarChar(200)")]
		public string NamePath
		{
			get
			{
				return this._NamePath;
			}
			set
			{
				if ((this._NamePath != value))
				{
					this.OnNamePathChanging(value);
					this.SendPropertyChanging();
					this._NamePath = value;
					this.SendPropertyChanged("NamePath");
					this.OnNamePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icon", DbType="NVarChar(200)")]
		public string Icon
		{
			get
			{
				return this._Icon;
			}
			set
			{
				if ((this._Icon != value))
				{
					this.OnIconChanging(value);
					this.SendPropertyChanging();
					this._Icon = value;
					this.SendPropertyChanged("Icon");
					this.OnIconChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DirType", DbType="Int NOT NULL")]
		public int DirType
		{
			get
			{
				return this._DirType;
			}
			set
			{
				if ((this._DirType != value))
				{
					this.OnDirTypeChanging(value);
					this.SendPropertyChanging();
					this._DirType = value;
					this.SendPropertyChanged("DirType");
					this.OnDirTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalFileCount", DbType="Int NOT NULL")]
		public int TotalFileCount
		{
			get
			{
				return this._TotalFileCount;
			}
			set
			{
				if ((this._TotalFileCount != value))
				{
					this.OnTotalFileCountChanging(value);
					this.SendPropertyChanging();
					this._TotalFileCount = value;
					this.SendPropertyChanged("TotalFileCount");
					this.OnTotalFileCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalFileSize", DbType="BigInt NOT NULL")]
		public long TotalFileSize
		{
			get
			{
				return this._TotalFileSize;
			}
			set
			{
				if ((this._TotalFileSize != value))
				{
					this.OnTotalFileSizeChanging(value);
					this.SendPropertyChanging();
					this._TotalFileSize = value;
					this.SendPropertyChanged("TotalFileSize");
					this.OnTotalFileSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalFileSizeText", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string TotalFileSizeText
		{
			get
			{
				return this._TotalFileSizeText;
			}
			set
			{
				if ((this._TotalFileSizeText != value))
				{
					this.OnTotalFileSizeTextChanging(value);
					this.SendPropertyChanging();
					this._TotalFileSizeText = value;
					this.SendPropertyChanged("TotalFileSizeText");
					this.OnTotalFileSizeTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUserID", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string CreateUserID
		{
			get
			{
				return this._CreateUserID;
			}
			set
			{
				if ((this._CreateUserID != value))
				{
					this.OnCreateUserIDChanging(value);
					this.SendPropertyChanging();
					this._CreateUserID = value;
					this.SendPropertyChanged("CreateUserID");
					this.OnCreateUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUserName", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string CreateUserName
		{
			get
			{
				return this._CreateUserName;
			}
			set
			{
				if ((this._CreateUserName != value))
				{
					this.OnCreateUserNameChanging(value);
					this.SendPropertyChanging();
					this._CreateUserName = value;
					this.SendPropertyChanged("CreateUserName");
					this.OnCreateUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateTime", DbType="DateTime NOT NULL")]
		public System.DateTime CreateTime
		{
			get
			{
				return this._CreateTime;
			}
			set
			{
				if ((this._CreateTime != value))
				{
					this.OnCreateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreateTime = value;
					this.SendPropertyChanged("CreateTime");
					this.OnCreateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsHide", DbType="Bit NOT NULL")]
		public bool IsHide
		{
			get
			{
				return this._IsHide;
			}
			set
			{
				if ((this._IsHide != value))
				{
					this.OnIsHideChanging(value);
					this.SendPropertyChanging();
					this._IsHide = value;
					this.SendPropertyChanged("IsHide");
					this.OnIsHideChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FS_FILE")]
	public partial class FS_FILE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _DirID;
		
		private string _DirPath;
		
		private string _Icon;
		
		private string _FileName;
		
		private string _Tags;
		
		private string _FileServer;
		
		private string _FilePath;
		
		private string _FileExt;
		
		private long _FileSize;
		
		private string _FileSizeText;
		
		private string _CreateUserID;
		
		private string _CreateUserName;
		
		private System.DateTime _CreateTime;
		
		private bool _IsDel;
		
		private System.DateTime _DelTime;
		
		private string _DataID;
		
		private string _CtrID;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnDirIDChanging(string value);
    partial void OnDirIDChanged();
    partial void OnDirPathChanging(string value);
    partial void OnDirPathChanged();
    partial void OnIconChanging(string value);
    partial void OnIconChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    partial void OnTagsChanging(string value);
    partial void OnTagsChanged();
    partial void OnFileServerChanging(string value);
    partial void OnFileServerChanged();
    partial void OnFilePathChanging(string value);
    partial void OnFilePathChanged();
    partial void OnFileExtChanging(string value);
    partial void OnFileExtChanged();
    partial void OnFileSizeChanging(long value);
    partial void OnFileSizeChanged();
    partial void OnFileSizeTextChanging(string value);
    partial void OnFileSizeTextChanged();
    partial void OnCreateUserIDChanging(string value);
    partial void OnCreateUserIDChanged();
    partial void OnCreateUserNameChanging(string value);
    partial void OnCreateUserNameChanged();
    partial void OnCreateTimeChanging(System.DateTime value);
    partial void OnCreateTimeChanged();
    partial void OnIsDelChanging(bool value);
    partial void OnIsDelChanged();
    partial void OnDelTimeChanging(System.DateTime value);
    partial void OnDelTimeChanged();
    partial void OnDataIDChanging(string value);
    partial void OnDataIDChanged();
    partial void OnCtrIDChanging(string value);
    partial void OnCtrIDChanged();
    #endregion
		
		public FS_FILE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DirID", DbType="NVarChar(200)")]
		public string DirID
		{
			get
			{
				return this._DirID;
			}
			set
			{
				if ((this._DirID != value))
				{
					this.OnDirIDChanging(value);
					this.SendPropertyChanging();
					this._DirID = value;
					this.SendPropertyChanged("DirID");
					this.OnDirIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DirPath", DbType="NVarChar(500)")]
		public string DirPath
		{
			get
			{
				return this._DirPath;
			}
			set
			{
				if ((this._DirPath != value))
				{
					this.OnDirPathChanging(value);
					this.SendPropertyChanging();
					this._DirPath = value;
					this.SendPropertyChanged("DirPath");
					this.OnDirPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icon", DbType="NVarChar(200)")]
		public string Icon
		{
			get
			{
				return this._Icon;
			}
			set
			{
				if ((this._Icon != value))
				{
					this.OnIconChanging(value);
					this.SendPropertyChanging();
					this._Icon = value;
					this.SendPropertyChanged("Icon");
					this.OnIconChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="NVarChar(200)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this.OnFileNameChanging(value);
					this.SendPropertyChanging();
					this._FileName = value;
					this.SendPropertyChanged("FileName");
					this.OnFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tags", DbType="NVarChar(500)")]
		public string Tags
		{
			get
			{
				return this._Tags;
			}
			set
			{
				if ((this._Tags != value))
				{
					this.OnTagsChanging(value);
					this.SendPropertyChanging();
					this._Tags = value;
					this.SendPropertyChanged("Tags");
					this.OnTagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileServer", DbType="NVarChar(200)")]
		public string FileServer
		{
			get
			{
				return this._FileServer;
			}
			set
			{
				if ((this._FileServer != value))
				{
					this.OnFileServerChanging(value);
					this.SendPropertyChanging();
					this._FileServer = value;
					this.SendPropertyChanged("FileServer");
					this.OnFileServerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FilePath", DbType="NVarChar(200)")]
		public string FilePath
		{
			get
			{
				return this._FilePath;
			}
			set
			{
				if ((this._FilePath != value))
				{
					this.OnFilePathChanging(value);
					this.SendPropertyChanging();
					this._FilePath = value;
					this.SendPropertyChanged("FilePath");
					this.OnFilePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileExt", DbType="NVarChar(200)")]
		public string FileExt
		{
			get
			{
				return this._FileExt;
			}
			set
			{
				if ((this._FileExt != value))
				{
					this.OnFileExtChanging(value);
					this.SendPropertyChanging();
					this._FileExt = value;
					this.SendPropertyChanged("FileExt");
					this.OnFileExtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileSize", DbType="BigInt NOT NULL")]
		public long FileSize
		{
			get
			{
				return this._FileSize;
			}
			set
			{
				if ((this._FileSize != value))
				{
					this.OnFileSizeChanging(value);
					this.SendPropertyChanging();
					this._FileSize = value;
					this.SendPropertyChanged("FileSize");
					this.OnFileSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileSizeText", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string FileSizeText
		{
			get
			{
				return this._FileSizeText;
			}
			set
			{
				if ((this._FileSizeText != value))
				{
					this.OnFileSizeTextChanging(value);
					this.SendPropertyChanging();
					this._FileSizeText = value;
					this.SendPropertyChanged("FileSizeText");
					this.OnFileSizeTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUserID", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string CreateUserID
		{
			get
			{
				return this._CreateUserID;
			}
			set
			{
				if ((this._CreateUserID != value))
				{
					this.OnCreateUserIDChanging(value);
					this.SendPropertyChanging();
					this._CreateUserID = value;
					this.SendPropertyChanged("CreateUserID");
					this.OnCreateUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUserName", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string CreateUserName
		{
			get
			{
				return this._CreateUserName;
			}
			set
			{
				if ((this._CreateUserName != value))
				{
					this.OnCreateUserNameChanging(value);
					this.SendPropertyChanging();
					this._CreateUserName = value;
					this.SendPropertyChanged("CreateUserName");
					this.OnCreateUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateTime", DbType="DateTime NOT NULL")]
		public System.DateTime CreateTime
		{
			get
			{
				return this._CreateTime;
			}
			set
			{
				if ((this._CreateTime != value))
				{
					this.OnCreateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreateTime = value;
					this.SendPropertyChanged("CreateTime");
					this.OnCreateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDel", DbType="Bit NOT NULL")]
		public bool IsDel
		{
			get
			{
				return this._IsDel;
			}
			set
			{
				if ((this._IsDel != value))
				{
					this.OnIsDelChanging(value);
					this.SendPropertyChanging();
					this._IsDel = value;
					this.SendPropertyChanged("IsDel");
					this.OnIsDelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DelTime", DbType="DateTime NOT NULL")]
		public System.DateTime DelTime
		{
			get
			{
				return this._DelTime;
			}
			set
			{
				if ((this._DelTime != value))
				{
					this.OnDelTimeChanging(value);
					this.SendPropertyChanging();
					this._DelTime = value;
					this.SendPropertyChanged("DelTime");
					this.OnDelTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataID", DbType="NVarChar(200)")]
		public string DataID
		{
			get
			{
				return this._DataID;
			}
			set
			{
				if ((this._DataID != value))
				{
					this.OnDataIDChanging(value);
					this.SendPropertyChanging();
					this._DataID = value;
					this.SendPropertyChanged("DataID");
					this.OnDataIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CtrID", DbType="NVarChar(200)")]
		public string CtrID
		{
			get
			{
				return this._CtrID;
			}
			set
			{
				if ((this._CtrID != value))
				{
					this.OnCtrIDChanging(value);
					this.SendPropertyChanging();
					this._CtrID = value;
					this.SendPropertyChanged("CtrID");
					this.OnCtrIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
