#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS2.OC.DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LygcjDB")]
	public partial class OCDataBaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertOC_AUTHORIZATION(OC_AUTHORIZATION instance);
    partial void UpdateOC_AUTHORIZATION(OC_AUTHORIZATION instance);
    partial void DeleteOC_AUTHORIZATION(OC_AUTHORIZATION instance);
    partial void InsertOC_NODE(OC_NODE instance);
    partial void UpdateOC_NODE(OC_NODE instance);
    partial void DeleteOC_NODE(OC_NODE instance);
    partial void InsertOC_EMPLOYEE(OC_EMPLOYEE instance);
    partial void UpdateOC_EMPLOYEE(OC_EMPLOYEE instance);
    partial void DeleteOC_EMPLOYEE(OC_EMPLOYEE instance);
    #endregion
		
		public OCDataBaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OCDataBaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OCDataBaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OCDataBaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<OC_AUTHORIZATION> OC_AUTHORIZATION
		{
			get
			{
				return this.GetTable<OC_AUTHORIZATION>();
			}
		}
		
		public System.Data.Linq.Table<OC_NODE> OC_NODE
		{
			get
			{
				return this.GetTable<OC_NODE>();
			}
		}
		
		public System.Data.Linq.Table<OC_EMPLOYEE> OC_EMPLOYEE
		{
			get
			{
				return this.GetTable<OC_EMPLOYEE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OC_AUTHORIZATION")]
	public partial class OC_AUTHORIZATION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _Name;
		
		private string _OrgIDs;
		
		private string _OrgNames;
		
		private string _ExcludeOrgIDs;
		
		private string _ExcludeOrgNames;
		
		private string _AuthorIDs;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnOrgIDsChanging(string value);
    partial void OnOrgIDsChanged();
    partial void OnOrgNamesChanging(string value);
    partial void OnOrgNamesChanged();
    partial void OnExcludeOrgIDsChanging(string value);
    partial void OnExcludeOrgIDsChanged();
    partial void OnExcludeOrgNamesChanging(string value);
    partial void OnExcludeOrgNamesChanged();
    partial void OnAuthorIDsChanging(string value);
    partial void OnAuthorIDsChanged();
    #endregion
		
		public OC_AUTHORIZATION()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(2000) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgIDs", DbType="NVarChar(MAX)")]
		public string OrgIDs
		{
			get
			{
				return this._OrgIDs;
			}
			set
			{
				if ((this._OrgIDs != value))
				{
					this.OnOrgIDsChanging(value);
					this.SendPropertyChanging();
					this._OrgIDs = value;
					this.SendPropertyChanged("OrgIDs");
					this.OnOrgIDsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrgNames", DbType="NVarChar(MAX)")]
		public string OrgNames
		{
			get
			{
				return this._OrgNames;
			}
			set
			{
				if ((this._OrgNames != value))
				{
					this.OnOrgNamesChanging(value);
					this.SendPropertyChanging();
					this._OrgNames = value;
					this.SendPropertyChanged("OrgNames");
					this.OnOrgNamesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExcludeOrgIDs", DbType="NVarChar(4000)")]
		public string ExcludeOrgIDs
		{
			get
			{
				return this._ExcludeOrgIDs;
			}
			set
			{
				if ((this._ExcludeOrgIDs != value))
				{
					this.OnExcludeOrgIDsChanging(value);
					this.SendPropertyChanging();
					this._ExcludeOrgIDs = value;
					this.SendPropertyChanged("ExcludeOrgIDs");
					this.OnExcludeOrgIDsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExcludeOrgNames", DbType="NVarChar(4000)")]
		public string ExcludeOrgNames
		{
			get
			{
				return this._ExcludeOrgNames;
			}
			set
			{
				if ((this._ExcludeOrgNames != value))
				{
					this.OnExcludeOrgNamesChanging(value);
					this.SendPropertyChanging();
					this._ExcludeOrgNames = value;
					this.SendPropertyChanged("ExcludeOrgNames");
					this.OnExcludeOrgNamesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthorIDs", DbType="NVarChar(MAX)")]
		public string AuthorIDs
		{
			get
			{
				return this._AuthorIDs;
			}
			set
			{
				if ((this._AuthorIDs != value))
				{
					this.OnAuthorIDsChanging(value);
					this.SendPropertyChanging();
					this._AuthorIDs = value;
					this.SendPropertyChanged("AuthorIDs");
					this.OnAuthorIDsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OC_NODE")]
	public partial class OC_NODE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _ParentID;
		
		private string _Name;
		
		private string _IDPath;
		
		private string _NamePath;
		
		private int _NType;
		
		private bool _Disabled;
		
		private bool _IsMainJob;
		
		private System.DateTime _CreateTime;
		
		private string _Ext001;
		
		private string _Ext002;
		
		private string _Ext003;
		
		private string _Ext004;
		
		private string _Ext005;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnParentIDChanging(string value);
    partial void OnParentIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnIDPathChanging(string value);
    partial void OnIDPathChanged();
    partial void OnNamePathChanging(string value);
    partial void OnNamePathChanged();
    partial void OnNTypeChanging(int value);
    partial void OnNTypeChanged();
    partial void OnDisabledChanging(bool value);
    partial void OnDisabledChanged();
    partial void OnIsMainJobChanging(bool value);
    partial void OnIsMainJobChanged();
    partial void OnCreateTimeChanging(System.DateTime value);
    partial void OnCreateTimeChanged();
    partial void OnExt001Changing(string value);
    partial void OnExt001Changed();
    partial void OnExt002Changing(string value);
    partial void OnExt002Changed();
    partial void OnExt003Changing(string value);
    partial void OnExt003Changed();
    partial void OnExt004Changing(string value);
    partial void OnExt004Changed();
    partial void OnExt005Changing(string value);
    partial void OnExt005Changed();
    #endregion
		
		public OC_NODE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="NVarChar(200)")]
		public string ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this.OnParentIDChanging(value);
					this.SendPropertyChanging();
					this._ParentID = value;
					this.SendPropertyChanged("ParentID");
					this.OnParentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(200)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPath", DbType="NVarChar(200)")]
		public string IDPath
		{
			get
			{
				return this._IDPath;
			}
			set
			{
				if ((this._IDPath != value))
				{
					this.OnIDPathChanging(value);
					this.SendPropertyChanging();
					this._IDPath = value;
					this.SendPropertyChanged("IDPath");
					this.OnIDPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamePath", DbType="NVarChar(200)")]
		public string NamePath
		{
			get
			{
				return this._NamePath;
			}
			set
			{
				if ((this._NamePath != value))
				{
					this.OnNamePathChanging(value);
					this.SendPropertyChanging();
					this._NamePath = value;
					this.SendPropertyChanged("NamePath");
					this.OnNamePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NType", DbType="Int NOT NULL")]
		public int NType
		{
			get
			{
				return this._NType;
			}
			set
			{
				if ((this._NType != value))
				{
					this.OnNTypeChanging(value);
					this.SendPropertyChanging();
					this._NType = value;
					this.SendPropertyChanged("NType");
					this.OnNTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Disabled", DbType="Bit NOT NULL")]
		public bool Disabled
		{
			get
			{
				return this._Disabled;
			}
			set
			{
				if ((this._Disabled != value))
				{
					this.OnDisabledChanging(value);
					this.SendPropertyChanging();
					this._Disabled = value;
					this.SendPropertyChanged("Disabled");
					this.OnDisabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMainJob", DbType="Bit NOT NULL")]
		public bool IsMainJob
		{
			get
			{
				return this._IsMainJob;
			}
			set
			{
				if ((this._IsMainJob != value))
				{
					this.OnIsMainJobChanging(value);
					this.SendPropertyChanging();
					this._IsMainJob = value;
					this.SendPropertyChanged("IsMainJob");
					this.OnIsMainJobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateTime", DbType="DateTime NOT NULL")]
		public System.DateTime CreateTime
		{
			get
			{
				return this._CreateTime;
			}
			set
			{
				if ((this._CreateTime != value))
				{
					this.OnCreateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreateTime = value;
					this.SendPropertyChanged("CreateTime");
					this.OnCreateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ext001", DbType="NVarChar(500)")]
		public string Ext001
		{
			get
			{
				return this._Ext001;
			}
			set
			{
				if ((this._Ext001 != value))
				{
					this.OnExt001Changing(value);
					this.SendPropertyChanging();
					this._Ext001 = value;
					this.SendPropertyChanged("Ext001");
					this.OnExt001Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ext002", DbType="NVarChar(500)")]
		public string Ext002
		{
			get
			{
				return this._Ext002;
			}
			set
			{
				if ((this._Ext002 != value))
				{
					this.OnExt002Changing(value);
					this.SendPropertyChanging();
					this._Ext002 = value;
					this.SendPropertyChanged("Ext002");
					this.OnExt002Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ext003", DbType="NVarChar(500)")]
		public string Ext003
		{
			get
			{
				return this._Ext003;
			}
			set
			{
				if ((this._Ext003 != value))
				{
					this.OnExt003Changing(value);
					this.SendPropertyChanging();
					this._Ext003 = value;
					this.SendPropertyChanged("Ext003");
					this.OnExt003Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ext004", DbType="NVarChar(500)")]
		public string Ext004
		{
			get
			{
				return this._Ext004;
			}
			set
			{
				if ((this._Ext004 != value))
				{
					this.OnExt004Changing(value);
					this.SendPropertyChanging();
					this._Ext004 = value;
					this.SendPropertyChanged("Ext004");
					this.OnExt004Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ext005", DbType="NVarChar(500)")]
		public string Ext005
		{
			get
			{
				return this._Ext005;
			}
			set
			{
				if ((this._Ext005 != value))
				{
					this.OnExt005Changing(value);
					this.SendPropertyChanging();
					this._Ext005 = value;
					this.SendPropertyChanged("Ext005");
					this.OnExt005Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OC_EMPLOYEE")]
	public partial class OC_EMPLOYEE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private string _ParentID;
		
		private string _Name;
		
		private string _IDPath;
		
		private string _NamePath;
		
		private int _NType;
		
		private bool _Disabled;
		
		private bool _IsMainJob;
		
		private System.DateTime _CreateTime;
		
		private string _LoginName;
		
		private string _PictureUrl;
		
		private string _UserName;
		
		private string _Gender;
		
		private string _PWD;
		
		private string _WX;
		
		private string _Email;
		
		private string _Tel;
		
		private string _Remark;
		
		private string _Jobs;
		
		private string _DataJson;
		
		private string _Ext001;
		
		private string _Ext002;
		
		private string _Ext003;
		
		private string _Ext004;
		
		private string _Ext005;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnParentIDChanging(string value);
    partial void OnParentIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnIDPathChanging(string value);
    partial void OnIDPathChanged();
    partial void OnNamePathChanging(string value);
    partial void OnNamePathChanged();
    partial void OnNTypeChanging(int value);
    partial void OnNTypeChanged();
    partial void OnDisabledChanging(bool value);
    partial void OnDisabledChanged();
    partial void OnIsMainJobChanging(bool value);
    partial void OnIsMainJobChanged();
    partial void OnCreateTimeChanging(System.DateTime value);
    partial void OnCreateTimeChanged();
    partial void OnLoginNameChanging(string value);
    partial void OnLoginNameChanged();
    partial void OnPictureUrlChanging(string value);
    partial void OnPictureUrlChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnPWDChanging(string value);
    partial void OnPWDChanged();
    partial void OnWXChanging(string value);
    partial void OnWXChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    partial void OnJobsChanging(string value);
    partial void OnJobsChanged();
    partial void OnDataJsonChanging(string value);
    partial void OnDataJsonChanged();
    partial void OnExt001Changing(string value);
    partial void OnExt001Changed();
    partial void OnExt002Changing(string value);
    partial void OnExt002Changed();
    partial void OnExt003Changing(string value);
    partial void OnExt003Changed();
    partial void OnExt004Changing(string value);
    partial void OnExt004Changed();
    partial void OnExt005Changing(string value);
    partial void OnExt005Changed();
    #endregion
		
		public OC_EMPLOYEE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="NVarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="NVarChar(200)")]
		public string ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this.OnParentIDChanging(value);
					this.SendPropertyChanging();
					this._ParentID = value;
					this.SendPropertyChanged("ParentID");
					this.OnParentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(200)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPath", DbType="NVarChar(200)")]
		public string IDPath
		{
			get
			{
				return this._IDPath;
			}
			set
			{
				if ((this._IDPath != value))
				{
					this.OnIDPathChanging(value);
					this.SendPropertyChanging();
					this._IDPath = value;
					this.SendPropertyChanged("IDPath");
					this.OnIDPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamePath", DbType="NVarChar(200)")]
		public string NamePath
		{
			get
			{
				return this._NamePath;
			}
			set
			{
				if ((this._NamePath != value))
				{
					this.OnNamePathChanging(value);
					this.SendPropertyChanging();
					this._NamePath = value;
					this.SendPropertyChanged("NamePath");
					this.OnNamePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NType", DbType="Int NOT NULL")]
		public int NType
		{
			get
			{
				return this._NType;
			}
			set
			{
				if ((this._NType != value))
				{
					this.OnNTypeChanging(value);
					this.SendPropertyChanging();
					this._NType = value;
					this.SendPropertyChanged("NType");
					this.OnNTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Disabled", DbType="Bit NOT NULL")]
		public bool Disabled
		{
			get
			{
				return this._Disabled;
			}
			set
			{
				if ((this._Disabled != value))
				{
					this.OnDisabledChanging(value);
					this.SendPropertyChanging();
					this._Disabled = value;
					this.SendPropertyChanged("Disabled");
					this.OnDisabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMainJob", DbType="Bit NOT NULL")]
		public bool IsMainJob
		{
			get
			{
				return this._IsMainJob;
			}
			set
			{
				if ((this._IsMainJob != value))
				{
					this.OnIsMainJobChanging(value);
					this.SendPropertyChanging();
					this._IsMainJob = value;
					this.SendPropertyChanged("IsMainJob");
					this.OnIsMainJobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateTime", DbType="DateTime NOT NULL")]
		public System.DateTime CreateTime
		{
			get
			{
				return this._CreateTime;
			}
			set
			{
				if ((this._CreateTime != value))
				{
					this.OnCreateTimeChanging(value);
					this.SendPropertyChanging();
					this._CreateTime = value;
					this.SendPropertyChanged("CreateTime");
					this.OnCreateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginName", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string LoginName
		{
			get
			{
				return this._LoginName;
			}
			set
			{
				if ((this._LoginName != value))
				{
					this.OnLoginNameChanging(value);
					this.SendPropertyChanging();
					this._LoginName = value;
					this.SendPropertyChanged("LoginName");
					this.OnLoginNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PictureUrl", DbType="NVarChar(2000)")]
		public string PictureUrl
		{
			get
			{
				return this._PictureUrl;
			}
			set
			{
				if ((this._PictureUrl != value))
				{
					this.OnPictureUrlChanging(value);
					this.SendPropertyChanging();
					this._PictureUrl = value;
					this.SendPropertyChanged("PictureUrl");
					this.OnPictureUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="NVarChar(200)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PWD", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string PWD
		{
			get
			{
				return this._PWD;
			}
			set
			{
				if ((this._PWD != value))
				{
					this.OnPWDChanging(value);
					this.SendPropertyChanging();
					this._PWD = value;
					this.SendPropertyChanged("PWD");
					this.OnPWDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WX", DbType="NVarChar(200)")]
		public string WX
		{
			get
			{
				return this._WX;
			}
			set
			{
				if ((this._WX != value))
				{
					this.OnWXChanging(value);
					this.SendPropertyChanging();
					this._WX = value;
					this.SendPropertyChanged("WX");
					this.OnWXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(200)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="NVarChar(200)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this.OnTelChanging(value);
					this.SendPropertyChanging();
					this._Tel = value;
					this.SendPropertyChanged("Tel");
					this.OnTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="NVarChar(2000)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jobs", DbType="NVarChar(2000)")]
		public string Jobs
		{
			get
			{
				return this._Jobs;
			}
			set
			{
				if ((this._Jobs != value))
				{
					this.OnJobsChanging(value);
					this.SendPropertyChanging();
					this._Jobs = value;
					this.SendPropertyChanged("Jobs");
					this.OnJobsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataJson", DbType="NVarChar(MAX)")]
		public string DataJson
		{
			get
			{
				return this._DataJson;
			}
			set
			{
				if ((this._DataJson != value))
				{
					this.OnDataJsonChanging(value);
					this.SendPropertyChanging();
					this._DataJson = value;
					this.SendPropertyChanged("DataJson");
					this.OnDataJsonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ext001", DbType="NVarChar(500)")]
		public string Ext001
		{
			get
			{
				return this._Ext001;
			}
			set
			{
				if ((this._Ext001 != value))
				{
					this.OnExt001Changing(value);
					this.SendPropertyChanging();
					this._Ext001 = value;
					this.SendPropertyChanged("Ext001");
					this.OnExt001Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ext002", DbType="NVarChar(500)")]
		public string Ext002
		{
			get
			{
				return this._Ext002;
			}
			set
			{
				if ((this._Ext002 != value))
				{
					this.OnExt002Changing(value);
					this.SendPropertyChanging();
					this._Ext002 = value;
					this.SendPropertyChanged("Ext002");
					this.OnExt002Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ext003", DbType="NVarChar(500)")]
		public string Ext003
		{
			get
			{
				return this._Ext003;
			}
			set
			{
				if ((this._Ext003 != value))
				{
					this.OnExt003Changing(value);
					this.SendPropertyChanging();
					this._Ext003 = value;
					this.SendPropertyChanged("Ext003");
					this.OnExt003Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ext004", DbType="NVarChar(500)")]
		public string Ext004
		{
			get
			{
				return this._Ext004;
			}
			set
			{
				if ((this._Ext004 != value))
				{
					this.OnExt004Changing(value);
					this.SendPropertyChanging();
					this._Ext004 = value;
					this.SendPropertyChanged("Ext004");
					this.OnExt004Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ext005", DbType="NVarChar(500)")]
		public string Ext005
		{
			get
			{
				return this._Ext005;
			}
			set
			{
				if ((this._Ext005 != value))
				{
					this.OnExt005Changing(value);
					this.SendPropertyChanging();
					this._Ext005 = value;
					this.SendPropertyChanged("Ext005");
					this.OnExt005Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
