//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS2.TestWebForm.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        SS2.TestWebForm.ServiceReference1.HelloWorldResponse HelloWorld(SS2.TestWebForm.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SS2.TestWebForm.ServiceReference1.HelloWorldResponse> HelloWorldAsync(SS2.TestWebForm.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 o 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveObj", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SS2.TestWebForm.ServiceReference1.ArrayOfString))]
        SS2.TestWebForm.ServiceReference1.SaveObjResponse SaveObj(SS2.TestWebForm.ServiceReference1.SaveObjRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveObj", ReplyAction="*")]
        System.Threading.Tasks.Task<SS2.TestWebForm.ServiceReference1.SaveObjResponse> SaveObjAsync(SS2.TestWebForm.ServiceReference1.SaveObjRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetObjResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetObj", ReplyAction="*")]
        SS2.TestWebForm.ServiceReference1.GetObjResponse GetObj(SS2.TestWebForm.ServiceReference1.GetObjRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetObj", ReplyAction="*")]
        System.Threading.Tasks.Task<SS2.TestWebForm.ServiceReference1.GetObjResponse> GetObjAsync(SS2.TestWebForm.ServiceReference1.GetObjRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 list 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveList", ReplyAction="*")]
        SS2.TestWebForm.ServiceReference1.SaveListResponse SaveList(SS2.TestWebForm.ServiceReference1.SaveListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveList", ReplyAction="*")]
        System.Threading.Tasks.Task<SS2.TestWebForm.ServiceReference1.SaveListResponse> SaveListAsync(SS2.TestWebForm.ServiceReference1.SaveListRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetListResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetList", ReplyAction="*")]
        SS2.TestWebForm.ServiceReference1.GetListResponse GetList(SS2.TestWebForm.ServiceReference1.GetListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetList", ReplyAction="*")]
        System.Threading.Tasks.Task<SS2.TestWebForm.ServiceReference1.GetListResponse> GetListAsync(SS2.TestWebForm.ServiceReference1.GetListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SS2.TestWebForm.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SS2.TestWebForm.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SS2.TestWebForm.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SS2.TestWebForm.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveObjRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveObj", Namespace="http://tempuri.org/", Order=0)]
        public SS2.TestWebForm.ServiceReference1.SaveObjRequestBody Body;
        
        public SaveObjRequest() {
        }
        
        public SaveObjRequest(SS2.TestWebForm.ServiceReference1.SaveObjRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveObjRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object o;
        
        public SaveObjRequestBody() {
        }
        
        public SaveObjRequestBody(object o) {
            this.o = o;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveObjResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveObjResponse", Namespace="http://tempuri.org/", Order=0)]
        public SS2.TestWebForm.ServiceReference1.SaveObjResponseBody Body;
        
        public SaveObjResponse() {
        }
        
        public SaveObjResponse(SS2.TestWebForm.ServiceReference1.SaveObjResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaveObjResponseBody {
        
        public SaveObjResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetObjRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetObj", Namespace="http://tempuri.org/", Order=0)]
        public SS2.TestWebForm.ServiceReference1.GetObjRequestBody Body;
        
        public GetObjRequest() {
        }
        
        public GetObjRequest(SS2.TestWebForm.ServiceReference1.GetObjRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetObjRequestBody {
        
        public GetObjRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetObjResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetObjResponse", Namespace="http://tempuri.org/", Order=0)]
        public SS2.TestWebForm.ServiceReference1.GetObjResponseBody Body;
        
        public GetObjResponse() {
        }
        
        public GetObjResponse(SS2.TestWebForm.ServiceReference1.GetObjResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetObjResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object GetObjResult;
        
        public GetObjResponseBody() {
        }
        
        public GetObjResponseBody(object GetObjResult) {
            this.GetObjResult = GetObjResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveList", Namespace="http://tempuri.org/", Order=0)]
        public SS2.TestWebForm.ServiceReference1.SaveListRequestBody Body;
        
        public SaveListRequest() {
        }
        
        public SaveListRequest(SS2.TestWebForm.ServiceReference1.SaveListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SS2.TestWebForm.ServiceReference1.ArrayOfString list;
        
        public SaveListRequestBody() {
        }
        
        public SaveListRequestBody(SS2.TestWebForm.ServiceReference1.ArrayOfString list) {
            this.list = list;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveListResponse", Namespace="http://tempuri.org/", Order=0)]
        public SS2.TestWebForm.ServiceReference1.SaveListResponseBody Body;
        
        public SaveListResponse() {
        }
        
        public SaveListResponse(SS2.TestWebForm.ServiceReference1.SaveListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaveListResponseBody {
        
        public SaveListResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetList", Namespace="http://tempuri.org/", Order=0)]
        public SS2.TestWebForm.ServiceReference1.GetListRequestBody Body;
        
        public GetListRequest() {
        }
        
        public GetListRequest(SS2.TestWebForm.ServiceReference1.GetListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetListRequestBody {
        
        public GetListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListResponse", Namespace="http://tempuri.org/", Order=0)]
        public SS2.TestWebForm.ServiceReference1.GetListResponseBody Body;
        
        public GetListResponse() {
        }
        
        public GetListResponse(SS2.TestWebForm.ServiceReference1.GetListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SS2.TestWebForm.ServiceReference1.ArrayOfString GetListResult;
        
        public GetListResponseBody() {
        }
        
        public GetListResponseBody(SS2.TestWebForm.ServiceReference1.ArrayOfString GetListResult) {
            this.GetListResult = GetListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : SS2.TestWebForm.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<SS2.TestWebForm.ServiceReference1.WebService1Soap>, SS2.TestWebForm.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SS2.TestWebForm.ServiceReference1.HelloWorldResponse SS2.TestWebForm.ServiceReference1.WebService1Soap.HelloWorld(SS2.TestWebForm.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SS2.TestWebForm.ServiceReference1.HelloWorldRequest inValue = new SS2.TestWebForm.ServiceReference1.HelloWorldRequest();
            inValue.Body = new SS2.TestWebForm.ServiceReference1.HelloWorldRequestBody();
            SS2.TestWebForm.ServiceReference1.HelloWorldResponse retVal = ((SS2.TestWebForm.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SS2.TestWebForm.ServiceReference1.HelloWorldResponse> SS2.TestWebForm.ServiceReference1.WebService1Soap.HelloWorldAsync(SS2.TestWebForm.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SS2.TestWebForm.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            SS2.TestWebForm.ServiceReference1.HelloWorldRequest inValue = new SS2.TestWebForm.ServiceReference1.HelloWorldRequest();
            inValue.Body = new SS2.TestWebForm.ServiceReference1.HelloWorldRequestBody();
            return ((SS2.TestWebForm.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SS2.TestWebForm.ServiceReference1.SaveObjResponse SS2.TestWebForm.ServiceReference1.WebService1Soap.SaveObj(SS2.TestWebForm.ServiceReference1.SaveObjRequest request) {
            return base.Channel.SaveObj(request);
        }
        
        public void SaveObj(object o) {
            SS2.TestWebForm.ServiceReference1.SaveObjRequest inValue = new SS2.TestWebForm.ServiceReference1.SaveObjRequest();
            inValue.Body = new SS2.TestWebForm.ServiceReference1.SaveObjRequestBody();
            inValue.Body.o = o;
            SS2.TestWebForm.ServiceReference1.SaveObjResponse retVal = ((SS2.TestWebForm.ServiceReference1.WebService1Soap)(this)).SaveObj(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SS2.TestWebForm.ServiceReference1.SaveObjResponse> SS2.TestWebForm.ServiceReference1.WebService1Soap.SaveObjAsync(SS2.TestWebForm.ServiceReference1.SaveObjRequest request) {
            return base.Channel.SaveObjAsync(request);
        }
        
        public System.Threading.Tasks.Task<SS2.TestWebForm.ServiceReference1.SaveObjResponse> SaveObjAsync(object o) {
            SS2.TestWebForm.ServiceReference1.SaveObjRequest inValue = new SS2.TestWebForm.ServiceReference1.SaveObjRequest();
            inValue.Body = new SS2.TestWebForm.ServiceReference1.SaveObjRequestBody();
            inValue.Body.o = o;
            return ((SS2.TestWebForm.ServiceReference1.WebService1Soap)(this)).SaveObjAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SS2.TestWebForm.ServiceReference1.GetObjResponse SS2.TestWebForm.ServiceReference1.WebService1Soap.GetObj(SS2.TestWebForm.ServiceReference1.GetObjRequest request) {
            return base.Channel.GetObj(request);
        }
        
        public object GetObj() {
            SS2.TestWebForm.ServiceReference1.GetObjRequest inValue = new SS2.TestWebForm.ServiceReference1.GetObjRequest();
            inValue.Body = new SS2.TestWebForm.ServiceReference1.GetObjRequestBody();
            SS2.TestWebForm.ServiceReference1.GetObjResponse retVal = ((SS2.TestWebForm.ServiceReference1.WebService1Soap)(this)).GetObj(inValue);
            return retVal.Body.GetObjResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SS2.TestWebForm.ServiceReference1.GetObjResponse> SS2.TestWebForm.ServiceReference1.WebService1Soap.GetObjAsync(SS2.TestWebForm.ServiceReference1.GetObjRequest request) {
            return base.Channel.GetObjAsync(request);
        }
        
        public System.Threading.Tasks.Task<SS2.TestWebForm.ServiceReference1.GetObjResponse> GetObjAsync() {
            SS2.TestWebForm.ServiceReference1.GetObjRequest inValue = new SS2.TestWebForm.ServiceReference1.GetObjRequest();
            inValue.Body = new SS2.TestWebForm.ServiceReference1.GetObjRequestBody();
            return ((SS2.TestWebForm.ServiceReference1.WebService1Soap)(this)).GetObjAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SS2.TestWebForm.ServiceReference1.SaveListResponse SS2.TestWebForm.ServiceReference1.WebService1Soap.SaveList(SS2.TestWebForm.ServiceReference1.SaveListRequest request) {
            return base.Channel.SaveList(request);
        }
        
        public void SaveList(SS2.TestWebForm.ServiceReference1.ArrayOfString list) {
            SS2.TestWebForm.ServiceReference1.SaveListRequest inValue = new SS2.TestWebForm.ServiceReference1.SaveListRequest();
            inValue.Body = new SS2.TestWebForm.ServiceReference1.SaveListRequestBody();
            inValue.Body.list = list;
            SS2.TestWebForm.ServiceReference1.SaveListResponse retVal = ((SS2.TestWebForm.ServiceReference1.WebService1Soap)(this)).SaveList(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SS2.TestWebForm.ServiceReference1.SaveListResponse> SS2.TestWebForm.ServiceReference1.WebService1Soap.SaveListAsync(SS2.TestWebForm.ServiceReference1.SaveListRequest request) {
            return base.Channel.SaveListAsync(request);
        }
        
        public System.Threading.Tasks.Task<SS2.TestWebForm.ServiceReference1.SaveListResponse> SaveListAsync(SS2.TestWebForm.ServiceReference1.ArrayOfString list) {
            SS2.TestWebForm.ServiceReference1.SaveListRequest inValue = new SS2.TestWebForm.ServiceReference1.SaveListRequest();
            inValue.Body = new SS2.TestWebForm.ServiceReference1.SaveListRequestBody();
            inValue.Body.list = list;
            return ((SS2.TestWebForm.ServiceReference1.WebService1Soap)(this)).SaveListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SS2.TestWebForm.ServiceReference1.GetListResponse SS2.TestWebForm.ServiceReference1.WebService1Soap.GetList(SS2.TestWebForm.ServiceReference1.GetListRequest request) {
            return base.Channel.GetList(request);
        }
        
        public SS2.TestWebForm.ServiceReference1.ArrayOfString GetList() {
            SS2.TestWebForm.ServiceReference1.GetListRequest inValue = new SS2.TestWebForm.ServiceReference1.GetListRequest();
            inValue.Body = new SS2.TestWebForm.ServiceReference1.GetListRequestBody();
            SS2.TestWebForm.ServiceReference1.GetListResponse retVal = ((SS2.TestWebForm.ServiceReference1.WebService1Soap)(this)).GetList(inValue);
            return retVal.Body.GetListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SS2.TestWebForm.ServiceReference1.GetListResponse> SS2.TestWebForm.ServiceReference1.WebService1Soap.GetListAsync(SS2.TestWebForm.ServiceReference1.GetListRequest request) {
            return base.Channel.GetListAsync(request);
        }
        
        public System.Threading.Tasks.Task<SS2.TestWebForm.ServiceReference1.GetListResponse> GetListAsync() {
            SS2.TestWebForm.ServiceReference1.GetListRequest inValue = new SS2.TestWebForm.ServiceReference1.GetListRequest();
            inValue.Body = new SS2.TestWebForm.ServiceReference1.GetListRequestBody();
            return ((SS2.TestWebForm.ServiceReference1.WebService1Soap)(this)).GetListAsync(inValue);
        }
    }
}
